# Aula 9: Introdução à Linguagem de Programação Python
Bem vindo ao Google Colaboratory!
Nós iremos utilizar essa plataforma para fazer nossas atividades com o Python. Vamos fazer alguns testes?

## Array e Matriz

Em Python, você pode criar uma matriz usando diferentes estruturas de dados. Os mais comuns são listas e matrizes NumPy. Veja como você pode trabalhar com arrays usando ambos os métodos:

Usando listas Python : as listas Python são versáteis e podem armazenar elementos de diferentes tipos de dados. Você pode criar e manipular arrays usando funções de lista integradas.
Criando uma matriz :

In [11]:
# Lista vazia
my_array = []

# Lista com elementos
my_array = [1, 2, 3, 4, 5]

In [12]:
# Acessando um elemento específico por índice
print(my_array[0])  # Output: 1
print(my_array[2])  # Output: 3

1
3


**Iterando** pelo array :

In [15]:
for element in my_array:
    print(element)

1
2
3
4
5


### Biblioteca **array**
Em Python o conceito de arrays multidimensionais não existe. O que existe é uma alternativa, que são os arrays encadeados, ou seja, cada elemento do array corresponde a outro array, ou como uma list de list em Java.

Veja um exemplo, na Listagem abaixo, de como pode ser criada uma matriz de **10** linhas e **5** colunas e como ela pode ser “varrida”.

In [16]:
import array as arr

numbers = arr.array('i',[10,20,30])

print(numbers[0]) # gets the 1st element
print(numbers[1]) # gets the 2nd element
print(numbers[2]) # gets the 3rd element



10
20
30


In [17]:
import array as arr

numbers = arr.array('i',[10,20,30,40])
for number in numbers:
    print(number)





10
20
30
40


## Utilizando a biblioteca NumPy

O Python tem um módulo especialmente desenvolvido para criar e tratar matrizes, o Numpy é uma biblioteca robusta que tem muitos métodos para se trabalhar com matrizes. Hoje entenderemos como podemos inicializar matrizes de diferente formas.

INSTALANDO A BIBLIOTECA NUMPY VIA PIP

In [18]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe -m pip install --upgrade pip' command.


## IMPORTANDO A BIBLIOTECA
Código:

In [6]:
# Convencionalmente a biblioteca é nomeada com o nome np
import numpy as np

### CRIANDO UMA MATRIZ

O Método numpy.array() nos permite a possibilidade de criar matrizes de n-dimensões.

Nesse exemplo criaremos uma matriz 2D com 2 Linhas e 3 Colunas.

Código:

In [19]:
# Matriz 2D
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Informações da Matriz criada
print(f"Dimensão da matriz: {matriz.ndim}")
print(f"Shape da Matriz: {matriz.shape}")
print(f"Número de elementos da Matriz: {matriz.size}")
print(f"Tipo dos elementos da Matriz: {matriz.dtype}")
print(f"Tamanho em Bytes de cada elemento da Matriz: {matriz.itemsize}")
print(f"Local da menmória onde está alocado essa matriz: {matriz.data}")

Dimensão da matriz: 2
Shape da Matriz: (2, 3)
Número de elementos da Matriz: 6
Tipo dos elementos da Matriz: int32
Tamanho em Bytes de cada elemento da Matriz: 4
Local da menmória onde está alocado essa matriz: <memory at 0x000001EE3346AE48>


Como inserir valores em matriz utilizando o FOR

In [7]:
import numpy as np

# Definir as dimensões da matriz
linhas = 3
colunas = 4

# Criar a matriz preenchida inicialmente com zeros (ou qualquer valor padrão)
matriz = np.zeros((linhas, colunas))

# Usar o loop for para inserir os dados na matriz
for i in range(linhas):
    for j in range(colunas):
        valor = float(input(f"Digite o valor para a posição [{i}, {j}]: "))
        matriz[i, j] = valor

print("Matriz resultante:")
print(matriz)

print (matriz[0][2])

Matriz resultante:
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
5.0


# Exercício 01

Faça um aplicação python que armazene 10 notas de um aluno em uma Array.
No final mostrar a media.
obs: altera para que o usuario posso lançar quantas notas queira


In [30]:
QN = int(input("Quantas notas ira lançar"))
notas = []

for i in range(QN):
    nota = float(input(f"Digite a nota {i + 1}: "))
    notas.append(nota)

media = sum(notas) / len(notas)

print(f"A média das notas é: {media}")


A média das notas é: 7.0


# Exercício 02

Escreva um programa Python NumPy que converte esta matriz de binários (0s e 1s) em uma matriz de booleanos (True e False). Dica: use o método astype() da NumPy para realizar esta tarefa.

obs: acresentei que usuario posso colocar o numero de linhas e colunas, e o binario fica no aleatorio

In [3]:
import numpy as np

num_linhas = int(input("Digite o número de linhas: "))
num_colunas = int(input("Digite o número de colunas: "))

matriz_binaria = np.random.randint(2, size=(num_linhas, num_colunas))

matriz_booleana = matriz_binaria.astype(bool)


print("\nMatriz binária:")
print(matriz_binaria)

print("\nMatriz de Booleanos:")
print(matriz_booleana)




Matriz binária:
[[0 0 0 1 1 1]
 [0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [1 1 0 0 0 1]
 [0 1 0 0 0 1]
 [0 0 1 0 0 1]]

Matriz de Booleanos:
[[False False False  True  True  True]
 [False False False False False  True]
 [False  True False False False False]
 [ True  True False False False  True]
 [False  True False False False  True]
 [False False  True False False  True]]


## Exercício 03
Verifique na matriz abaixo qual numero é par e impar.

```
Matriz: 4 x 3
     3     4     3     
     5     4     8   
     44    66    6   
     6     9     10
```

fora adicionar quantas linhas, colunas e poder colocar os dados, deixar o impar e par na em tabela

In [2]:
import numpy as np

linhas = int(input("Quantas linhas você quer? "))
colunas = int(input("Quantas colunas você quer? "))
matriz = np.zeros((linhas, colunas), dtype=int)

for i in range(linhas):
    for j in range(colunas):
        valor = int(input(f"Digite o valor para a posição [{i}, {j}]: "))
        matriz[i, j] = valor
        if valor % 2 == 0:
            print("PAR", end=' ')
        else:
            print("IMPAR", end=' ')
    print() 
print("\nMatriz resultante:")
print(matriz)


IMPAR PAR IMPAR PAR 
PAR IMPAR PAR IMPAR 
IMPAR PAR IMPAR PAR 
PAR IMPAR PAR IMPAR 

Matriz resultante:
[[1 2 1 2]
 [2 1 2 1]
 [1 2 1 2]
 [2 1 2 1]]


## Exercício 04
Verifique na matriz abaixo qual numero é primo

In [2]:
import numpy as np

linhas = int(input("Quantas linhas você quer? "))
colunas = int(input("Quantas colunas você quer? "))
matriz = np.zeros((linhas, colunas), dtype=int)

for l in range(linhas):
    for c in range(colunas):
        numero = int(input(f"Digite o número para a posição ({l}, {c}): "))
        matriz[l][c] = numero

for l in range(linhas):
    for c in range(colunas):
        numero = matriz[l][c]
        eh_primo = True

        if numero < 2:
            eh_primo = False
        else:
            for i in range(2, int(np.sqrt(numero)) + 1):
                if numero % i == 0:
                    eh_primo = False
                    break

        if eh_primo:
            print(f"O número na posição ({l}, {c}), {numero}, é primo.")
        else:
            print(f"O número na posição ({l}, {c}), {numero}, não é primo.")


O número na posição (0, 0), 2, é primo.
O número na posição (0, 1), 2, é primo.
O número na posição (1, 0), 2, é primo.
O número na posição (1, 1), 2, é primo.


In [ ]:
#Teste de Primalidade de Fermat
import random

def mod_exp(base, exp, mod):
    result = 1
    base = base % mod
    while exp > 0:
        if exp % 2 == 1:
            result = (result * base) % mod
        exp = exp // 2
        base = (base * base) % mod
    return result

def fermat_test(n, k=5):
    if n == 2 or n == 3:
        return True

    if n <= 1 or n % 2 == 0:
        return False

    for _ in range(k):
        a = random.randint(2, n - 2)
        if mod_exp(a, n - 1, n) != 1:
            return False

    return True

numero_usuario = int(input("Digite um número para verificar se é primo: "))

if fermat_test(numero_usuario):
    print(f"{numero_usuario} é provavelmente primo.")
else:
    print(f"{numero_usuario} é composto.")


In [1]:
# Mostrando os numeros primos de 0 a 1000
import random

def mod_exp(base, exp, mod):
    result = 1
    base = base % mod
    while exp > 0:
        if exp % 2 == 1:
            result = (result * base) % mod
        exp = exp // 2
        base = (base * base) % mod
    return result

def fermat_test(n, k=5):
    if n == 2 or n == 3:
        return True

    if n <= 1 or n % 2 == 0:
        return False

    for _ in range(k):
        a = random.randint(2, n - 2)
        if mod_exp(a, n - 1, n) != 1:
            return False

    return True

for num in range(1, 1000):
    if fermat_test(num):
        print(num, end=' ')


2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491 499 503 509 521 523 541 547 557 563 569 571 577 587 593 599 601 607 613 617 619 631 641 643 647 653 659 661 673 677 683 691 701 709 719 727 733 739 743 751 757 761 769 773 787 797 809 811 821 823 827 829 839 853 857 859 863 877 881 883 887 907 911 919 929 937 941 947 953 967 971 977 983 991 997 