# Aula 9: Introdução à Linguagem de Programação Python
Bem vindo ao Google Colaboratory!
Nós iremos utilizar essa plataforma para fazer nossas atividades com o Python. Vamos fazer alguns testes?

## Array e Matriz

Em Python, você pode criar uma matriz usando diferentes estruturas de dados. Os mais comuns são listas e matrizes NumPy. Veja como você pode trabalhar com arrays usando ambos os métodos:

Usando listas Python : as listas Python são versáteis e podem armazenar elementos de diferentes tipos de dados. Você pode criar e manipular arrays usando funções de lista integradas.
Criando uma matriz :

In [11]:
# Lista vazia
my_array = []

# Lista com elementos
my_array = [1, 2, 3, 4, 5]

In [12]:
# Acessando um elemento específico por índice
print(my_array[0])  # Output: 1
print(my_array[2])  # Output: 3

1
3


**Iterando** pelo array :

In [15]:
for element in my_array:
    print(element)

1
2
3
4
5


### Biblioteca **array**
Em Python o conceito de arrays multidimensionais não existe. O que existe é uma alternativa, que são os arrays encadeados, ou seja, cada elemento do array corresponde a outro array, ou como uma list de list em Java.

Veja um exemplo, na Listagem abaixo, de como pode ser criada uma matriz de **10** linhas e **5** colunas e como ela pode ser “varrida”.

In [16]:
import array as arr

numbers = arr.array('i',[10,20,30])

print(numbers[0]) # gets the 1st element
print(numbers[1]) # gets the 2nd element
print(numbers[2]) # gets the 3rd element



10
20
30


In [17]:
import array as arr

numbers = arr.array('i',[10,20,30,40])
for number in numbers:
    print(number)





10
20
30
40


## Utilizando a biblioteca NumPy

O Python tem um módulo especialmente desenvolvido para criar e tratar matrizes, o Numpy é uma biblioteca robusta que tem muitos métodos para se trabalhar com matrizes. Hoje entenderemos como podemos inicializar matrizes de diferente formas.

INSTALANDO A BIBLIOTECA NUMPY VIA PIP

In [18]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe -m pip install --upgrade pip' command.


## IMPORTANDO A BIBLIOTECA
Código:

In [6]:
# Convencionalmente a biblioteca é nomeada com o nome np
import numpy as np

### CRIANDO UMA MATRIZ

O Método numpy.array() nos permite a possibilidade de criar matrizes de n-dimensões.

Nesse exemplo criaremos uma matriz 2D com 2 Linhas e 3 Colunas.

Código:

In [19]:
# Matriz 2D
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Informações da Matriz criada
print(f"Dimensão da matriz: {matriz.ndim}")
print(f"Shape da Matriz: {matriz.shape}")
print(f"Número de elementos da Matriz: {matriz.size}")
print(f"Tipo dos elementos da Matriz: {matriz.dtype}")
print(f"Tamanho em Bytes de cada elemento da Matriz: {matriz.itemsize}")
print(f"Local da menmória onde está alocado essa matriz: {matriz.data}")

Dimensão da matriz: 2
Shape da Matriz: (2, 3)
Número de elementos da Matriz: 6
Tipo dos elementos da Matriz: int32
Tamanho em Bytes de cada elemento da Matriz: 4
Local da menmória onde está alocado essa matriz: <memory at 0x000001EE3346AE48>


Como inserir valores em matriz utilizando o FOR

In [7]:
import numpy as np

# Definir as dimensões da matriz
linhas = 3
colunas = 4

# Criar a matriz preenchida inicialmente com zeros (ou qualquer valor padrão)
matriz = np.zeros((linhas, colunas))

# Usar o loop for para inserir os dados na matriz
for i in range(linhas):
    for j in range(colunas):
        valor = float(input(f"Digite o valor para a posição [{i}, {j}]: "))
        matriz[i, j] = valor

print("Matriz resultante:")
print(matriz)

print (matriz[0][2])

Matriz resultante:
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
5.0


# Exercício 01

Faça um aplicação python que armazene 10 notas de um aluno em uma Array.
No final mostrar a media.



In [30]:
QN = int(input("Quantas notas ira lançar"))
notas = []

for i in range(QN):
    nota = float(input(f"Digite a nota {i + 1}: "))
    notas.append(nota)

media = sum(notas) / len(notas)

print(f"A média das notas é: {media}")


A média das notas é: 7.0


# Exercício 02

Escreva um programa Python NumPy que converte esta matriz de binários (0s e 1s) em uma matriz de booleanos (True e False). Dica: use o método astype() da NumPy para realizar esta tarefa.

In [6]:
import numpy as np

matriz_binaria = np.array([[0, 1, 0], [1, 0, 1], [0, 0, 1]])

matriz_booleana = matriz_binaria.astype(bool)

print("Matriz binário:")
print(matriz_binaria)

print("\nMatriz de Booleanos:")
print(matriz_booleana)


Matriz binário:
[[0 1 0]
 [1 0 1]
 [0 0 1]]

Matriz de Booleanos:
[[False  True False]
 [ True False  True]
 [False False  True]]


## Exercício 03
Verifique na matriz abaixo qual numero é par e impar.

```
Matriz: 4 x 3
     3     4     3     
     5     4     8   
     44    66    6   
     6     9     10
```

In [2]:
import numpy as np

linhas = int(input("Quantas linhas você quer? "))
colunas = int(input("Quantas colunas você quer? "))
matriz = np.zeros((linhas, colunas))

for i in range(linhas):
    for j in range(colunas):
        valor = float(input(f"Digite o valor para a posição [{i}, {j}]: "))
        matriz[i, j] = valor
        if int(valor) % 2 == 0:
            print("PAR", end=' ')
        else:
            print("IMPAR", end=' ')

print("\nMatriz resultante:")
print(matriz)

IMPAR PAR IMPAR IMPAR 
Matriz resultante:
[[1. 2.]
 [3. 1.]]


## Exercício 04
Verifique na matriz abaixo qual numero é primo

In [2]:
n = int(input("Verificar numeros primos ate: "))
mult=0

for count in range(2,n):
    if (n % count == 0):
        print("Múltiplo de",count)
        mult += 1

if(mult==0):
    print("É primo")
else:
    print("Tem",mult," múltiplos acima de 2 e abaixo de",n)

Múltiplo de 2
Múltiplo de 4
Múltiplo de 5
Múltiplo de 8
Múltiplo de 10
Múltiplo de 16
Múltiplo de 20
Múltiplo de 25
Múltiplo de 32
Múltiplo de 40
Múltiplo de 50
Múltiplo de 80
Múltiplo de 100
Múltiplo de 125
Múltiplo de 160
Múltiplo de 200
Múltiplo de 250
Múltiplo de 400
Múltiplo de 500
Múltiplo de 625
Múltiplo de 800
Múltiplo de 1000
Múltiplo de 1250
Múltiplo de 2000
Múltiplo de 2500
Múltiplo de 4000
Múltiplo de 5000
Múltiplo de 10000
Tem 28  múltiplos acima de 2 e abaixo de 20000
